import { readFile } from 'node:fs/promises';
import path from 'node:path';

import { describe, expect, it } from 'vitest';

import {
  GENERATED_SECTIONS,
  buildHandoffDocument,
  parseNameStatus,
  renderGeneratedSections,
  tailLines,
} from '../../scripts/release/handoff-facts.mjs';
import { REQUIRED_HANDOFF_SECTIONS } from '../../scripts/foundation/operating-model.mjs';

const repositoryRoot = path.resolve(import.meta.dirname, '../..');

function facts(overrides = {}) {
  return {
    taskId: 'SBLA-012',
    branch: 'codex/SBLA-012-design-system',
    baseCommit: 'a'.repeat(40),
    headCommit: 'b'.repeat(40),
    headTree: 'c'.repeat(40),
    worktreeClean: true,
    nodeVersion: 'v24.20.0',
    pnpmVersion: '11.24.0',
    changedPaths: [
      { status: 'M', path: 'src/styles/global.css' },
      { status: 'A', path: 'src/pages/muscles/[slug].astro' },
    ],
    checks: [
      { command: 'pnpm verify', exitCode: 0, outputTail: 'Tests 330 passed' },
    ],
    ...overrides,
  };
}

describe('handoff facts', () => {
  it('parses NUL-delimited name-status output in stable path order', () => {
    expect(parseNameStatus('M\0src/b.ts\0A\0docs/a.md\0d\0old.txt\0')).toEqual([
      { status: 'A', path: 'docs/a.md' },
      { status: 'D', path: 'old.txt' },
      { status: 'M', path: 'src/b.ts' },
    ]);
  });

  it('rejects a truncated name-status diff instead of dropping a path', () => {
    expect(() => parseNameStatus('M\0src/b.ts\0A\0')).toThrow(
      'Could not parse the complete name-status diff.',
    );
  });

  it('keeps only the tail of long command output', () => {
    const output = Array.from(
      { length: 40 },
      (_, index) => `line ${index}`,
    ).join('\n');
    expect(tailLines(output, 3)).toBe('line 37\nline 38\nline 39');
  });

  it('renders exact commits, tree, runtime, and every changed path', () => {
    const sections = renderGeneratedSections(facts());

    expect(Object.keys(sections)).toEqual([...GENERATED_SECTIONS]);
    expect(sections['## Inputs and exact paths']).toContain(
      `\`${'a'.repeat(40)}\``,
    );
    expect(sections['## Inputs and exact paths']).toContain(
      `\`${'c'.repeat(40)}\``,
    );
    expect(sections['## Inputs and exact paths']).toContain('v24.20.0');
    expect(sections['## Files created or modified']).toContain(
      '- `src/pages/muscles/[slug].astro` — added',
    );
    expect(sections['## Tests/checks run and results']).toContain(
      '`pnpm verify` — PASS',
    );
  });

  it('reports failed checks and a dirty tree rather than hiding them', () => {
    const sections = renderGeneratedSections(
      facts({
        worktreeClean: false,
        checks: [{ command: 'pnpm verify', exitCode: 1, outputTail: 'FAIL' }],
      }),
    );

    expect(sections['## Tests/checks run and results']).toContain(
      'FAIL (exit 1)',
    );
    expect(sections['## Inputs and exact paths']).toContain('dirty');
  });

  it('says plainly when no checks ran', () => {
    expect(
      renderGeneratedSections(facts({ checks: [] }))[
        '## Tests/checks run and results'
      ],
    ).toContain('was not run');
  });

  it('rejects abbreviated hashes and malformed task IDs', () => {
    expect(() =>
      renderGeneratedSections(facts({ headCommit: 'bbbbbbb' })),
    ).toThrow('full 40-character SHA');
    expect(() => renderGeneratedSections(facts({ taskId: 'task-12' }))).toThrow(
      'Task ID',
    );
  });

  it('builds a skeleton from the real template with every required heading in order', async () => {
    const template = await readFile(
      path.join(repositoryRoot, 'docs/runbooks/handoff-template.md'),
      'utf8',
    );
    const document = buildHandoffDocument(template, facts(), 'Design system');
    const headings = document.match(/^## .+$/gm) ?? [];

    expect(document.startsWith('# Handoff: SBLA-012 — Design system')).toBe(
      true,
    );
    expect(headings).toEqual([...REQUIRED_HANDOFF_SECTIONS]);
    expect(document).toContain('generated by pnpm handoff');
    expect(document).toContain(`\`${'b'.repeat(40)}\``);
  });
});
